# Generated by Django 5.1.5 on 2025-02-03 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkiObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('distance', models.FloatField(blank=True, help_text='Distance in miles', null=True)),
                ('vertical_gain', models.IntegerField(blank=True, help_text='Vertical gain in feet', null=True)),
                ('area', models.CharField(blank=True, max_length=200, null=True)),
                ('aspect', models.CharField(blank=True, max_length=100, null=True)),
                ('trip_report_link', models.URLField(blank=True, null=True)),
                ('interest_level', models.CharField(blank=True, choices=[('BURNING', 'Burning'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('MILD', 'Mild')], max_length=20, null=True)),
                ('done_before', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('skill_level', models.CharField(blank=True, choices=[('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Advanced'), ('4', 'Expert'), ('5', 'Extreme')], max_length=1, null=True)),
                ('strenuous_level', models.CharField(blank=True, choices=[('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Advanced'), ('4', 'Expert'), ('5', 'Extreme')], max_length=1, null=True)),
                ('lowest_elevation', models.IntegerField(blank=True, null=True)),
                ('highest_elevation', models.IntegerField(blank=True, null=True)),
                ('best_season', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True)),
                ('interested_people', models.TextField(blank=True)),
                ('gpx_file', models.FileField(blank=True, null=True, upload_to='gpx_files/')),
                ('strava_embed_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-interest_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InterestedParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_parties', to='objectives.skiobjective')),
            ],
            options={
                'verbose_name_plural': 'Interested Parties',
            },
        ),
    ]
